- name: Deploy to BlueField DPU
  hosts: dpu
  tasks:
    - name: Sync project files
      ansible.posix.synchronize:
        src: ./your_project_dir/
        dest: /home/bluefield/my_project/
        delete: yes

    - name: Build project
      shell: ./build.sh
      args:
        chdir: /home/bluefield/my_project

    - name: Run tests
      shell: ./test.sh
      args:
        chdir: /home/bluefield/my_project

    - name: Run application
      shell: nohup ./run.sh &
      args:
        chdir: /home/bluefield/my_project
