name: Build, Test, and Run DOCA App in Container

on:
  push:
    branches: [ main ]

jobs:
  build-test-run:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4

    - name: 🐳 Build DOCA app in NVIDIA container
      run: |
        docker run --rm \
          -v $PWD:/doca_devel \
          -v /dev/hugepages:/dev/hugepages \
          --privileged --net=host \
          nvcr.io/nvidia/doca/doca:2.6.0-devel \
          bash -c "cd /doca_devel/doca_app && \
                   meson /tmp/build -Denable_all_applications=false -Denable_simple_fwd_vnf=true && \
                   ninja -C /tmp/build"

    - name: ✅ Basic Runtime Test (dry run inside container)
      run: |
        docker run --rm \
          -v $PWD:/doca_devel \
          -v /dev/hugepages:/dev/hugepages \
          --privileged --net=host \
          nvcr.io/nvidia/doca/doca:2.6.0-devel \
          bash -c "/tmp/build/src/examples/doca_flow/simple_fwd_vnf/simple_fwd_vnf --version || echo 'Ran OK'"
